version: "3"
services:
  hostplat-client:
    image: hostplat-client
    build:
      context: hostplat-client
      dockerfile: Dockerfile
    container_name: hostplat-client-container
    networks:
      hostplat:
        ipv4_address: 172.22.0.11
    ports:
      - 4200:4200
  hostplat-server:
    image: hostplat-server
    build:
      context: hostplat-server
      dockerfile: Dockerfile
    container_name: hostplat-server-container
    networks:
      hostplat:
        ipv4_address: 172.22.0.12
    ports:
      - 9000:9000
  elasticsearch:
    labels:
      com.example.service: "es"
      com.example.description: "For searching and indexing data"
    image: elasticsearch:5.4
    container_name: myapp_elasticsearch
    volumes:
      - ./esdata:/usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    labels:
      com.example.service: "kibana"
      com.example.description: "Data visualisation and for log aggregation"
    image: kibana:5.4.3
    container_name: myapp_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  logstash:
    labels:
      com.example.service: "logstash"
      com.example.description: "For logging data"
    image: logstash:5.4.3
    container_name: myapp_logstash
    volumes:
      - ./config/logstash:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "5959:5959"
  influxdb:
    container_name: myapp_influxdb
    image: influxdb:1.0.2
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    restart: always
  grafana:
    container_name: myapp_grafana
    image: grafana/grafana:4.3.2
    ports:
      - "3000:3000"
    links:
      - influxdb
    restart: always

networks:
  hostplat:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24